;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
;; (setq user-full-name "John Doe"
;;      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;; (setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Stefano Coretta")

(setq doom-theme 'doom-dracula
      doom-dracula-brighter-modeline t)

;; make background black for better readability
(custom-set-faces!
  '(default :background "black"))

(setq doom-font (font-spec :family "Hasklug Nerd Font Mono" :size 14)
      doom-big-font (font-spec :family "Hasklug Nerd Font Mono" :size 24)
      doom-variable-pitch-font (font-spec :family "Lato" :size 14))

(setq-default tab-width 2)

(add-to-list 'initial-frame-alist '(fullscreen . maximized))

(setq confirm-kill-emacs nil)

(setq display-line-numbers-type t)

(after! org
  (remove-hook 'after-save-hook #'+literate-recompile-maybe-h))

(setq +workspaces-on-switch-project-behavior t)

(map!
 :leader
 :prefix ("a" . "custom")
 :desc "Open agenda view" "a" #'org-agenda-list
 :desc "Search in bibliography" "b" #'ivy-bibtex
 :desc "Open calendar" "c" #'cfw:open-org-calendar
 :desc "Open agenda file" "A" (lambda () (interactive) (find-file "/Users/ste/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/agenda.org"))
 :desc "Open bibliograpy file" "B" (lambda () (interactive) (find-file "~/texmf/bibtex/bib/linguistics.bib"))
 :desc "Open file with external app" "e" #'open-in-external-app
 :desc "List GitHub issues" "f" #'forge-list-owned-issues)

(define-key evil-normal-state-map "u" 'undo-fu-only-undo)
(define-key evil-normal-state-map "\C-r" 'undo-fu-only-redo)

(after! org
  (map! :map org-mode-map
        :n "M-j" #'org-metadown
        :n "M-k" #'org-metaup ))

(defhydra hydra-window ()
   "
Movement^^        ^Split^         ^Switch^      ^Resize^
----------------------------------------------------------------
_h_ ←        _v_ertical       _b_uffer          _q_ X←
_j_ ↓        _x_ horizontal   _f_ind files      _w_ X↓
_k_ ↑        _z_ undo         _a_ce 1           _e_ X↑
_l_ →        _Z_ reset        _s_wap            _r_ X→
_F_ollow     _D_lt Other      _S_ave            max_i_mize
_SPC_ cancel _o_nly this      _d_elete
"
   ("h" windmove-left )
   ("j" windmove-down )
   ("k" windmove-up )
   ("l" windmove-right )
   ("q" hydra-move-splitter-left)
   ("w" hydra-move-splitter-down)
   ("e" hydra-move-splitter-up)
   ("r" hydra-move-splitter-right)
   ("b" helm-mini)
   ("f" helm-find-files)
   ("F" follow-mode)
   ("a" (lambda ()
          (interactive)
          (ace-window 1)
          (add-hook 'ace-window-end-once-hook
                    'hydra-window/body))
       )
   ("v" (lambda ()
          (interactive)
          (split-window-right)
          (windmove-right))
       )
   ("x" (lambda ()
          (interactive)
          (split-window-below)
          (windmove-down))
       )
   ("s" (lambda ()
          (interactive)
          (ace-window 4)
          (add-hook 'ace-window-end-once-hook
                    'hydra-window/body)))
   ("S" save-buffer)
   ("d" delete-window)
   ("D" (lambda ()
          (interactive)
          (ace-window 16)
          (add-hook 'ace-window-end-once-hook
                    'hydra-window/body))
       )
   ("o" delete-other-windows)
   ("i" ace-maximize-window)
   ("z" (progn
          (winner-undo)
          (setq this-command 'winner-undo))
   )
   ("Z" winner-redo)
   ("SPC" nil)
   )

(map!
 :leader
 :desc "Windows" "e" #'hydra-window/body )

(defhydra hydra-smerge ()
   "
Movement^^^^               Merge Action^^           Other
---------------------^^^^  -------------------^^    -----------
_n_/_p_  next/prev hunk    _l_ keep lower            _u_ undo
_j_/_k_  move up/down      _u_ keep upper            _r_ resolve
^^^^                       _a_ keep all              _R_ refine
^^^^                       _c_ keep current          _SPC_ quit
^^^^                       _C_ combine with next
"
  ("n" smerge-next)
  ("p" smerge-prev)
  ("j" evil-next-line)
  ("k" evil-previous-line)
  ("a" smerge-keep-all)
  ("l" smerge-keep-lower)
  ("u" smerge-keep-upper)
  ("c" smerge-keep-current)
  ("C" smerge-combine-with-next)
  ("r" smerge-resolve)
  ("R" smerge-refine)
  ("u" undo-tree-undo)
  ("SPC" nil)
  )

(map!
 :leader
 :desc "Smerge" "r" #'hydra-smerge/body )

;; First day of the week
(setq calendar-week-start-day 1) ; 0:Sunday, 1:Monday

(setq deft-directory "/Users/ste/Library/Mobile Documents/com~apple~CloudDocs/drive/deft"
      deft-extensions '("org", "md", "txt", "tex")
      deft-recursive t)

(setq auth-sources '("~/.authinfo")
      forge-owned-accounts '(("stefanocoretta" . nil)
                             ("learnB4SS" . nil)
                             ("many-speech-analyses" . nil)))

(setq magit-repository-directories
      '(("~/repos" . 2)))

(setq magit-repolist-column-flag-alist
             '((magit-untracked-files . "  ❕️  ")
               (magit-unstaged-files . "  🟠  ")
               (magit-staged-files . "  🟢  ")))

(setq magit-repolist-columns
  '(("Name"     25 magit-repolist-column-ident nil)
    ("Version"  25 magit-repolist-column-version nil)
    (""   5 magit-repolist-column-flag nil)
    ("B<U"      3 magit-repolist-column-unpulled-from-upstream
      ((:right-align t)
       (:help-echo "Upstream changes not in branch")))
    ("B>U"      3 magit-repolist-column-unpushed-to-upstream
      ((:right-align t)
       (:help-echo "Local changes not in upstream")))
    ("Path"     99 magit-repolist-column-path nil)))

(setq projectile-project-search-path
      '("~/repos" "~/repos/conlang" "~/repos/research" "~/repos/software" "~/repos/typography" "~/repos/web" "~/repos/b4ss" "~/repos/many-speech" "~/repos/teaching" "~/repos/intRo")
      projectile-auto-discover nil)

(setq org-roam-directory (file-truename "/Users/ste/Library/Mobile Documents/com~apple~CloudDocs/drive/roam") )

(setq org-roam-capture-templates
      '(("d" "default" plain #'org-roam-capture--get-point "%?" :file-name "${slug}" :head "#+title: ${title}\n#+date: %t\n" :unnarrowed t)))

(setq ispell-dictionary "en")
(remove-hook 'text-mode-hook #'spell-fu-mode)

(use-package! zetteldeft
  :after deft
  :config
    (zetteldeft-set-classic-keybindings))

(map!
  :leader
  :prefix ("d" . "deft")
  :desc "deft" "d" #'deft
  :desc "new serch" "D" #'zetteldeft-deft-new-search
  :desc "refresh" "R" #'deft-refresh
  :desc "search at point" "s" #'zetteldeft-search-at-point
  :desc "search current id" "c" #'zetteldeft-search-current-id
  :desc "follow link" "f" #'zetteldeft-follow-link
  :desc "avy file othe window" "F" #'zetteldeft-avy-file-search-ace-window
  :desc "browse" "." #'zetteldeft-browse
  :desc "go home" "h" #'zetteldeft-go-home
  :desc "avy link search" "l" #'zetteldeft-avy-link-search
  :desc "avy tag search" "t" #'zetteldeft-avy-tag-search
  :desc "tag list" "T" #'zetteldeft-tag-buffer
  :desc "insert tag" "#" #'zetteldeft-tag-insert
  :desc "search tag" "/" #'zetteldeft-search-tag
  :desc "insert id" "i" #'zetteldeft-find-file-id-insert
  :desc "insert full title" "I" #'zetteldeft-find-file-full-title-insert
  :desc "find file" "o" #'zetteldeft-find-file
  :desc "new file" "n" #'zetteldeft-new-file
  :desc "new file & link" "N" #'zetteldeft-new-file-and-link
  :desc "new file & backlink" "B" #'zetteldeft-new-file-and-backlink
  :desc "add link" "b" #'zetteldeft-backlink-add
  :desc "rename" "r" #'zetteldeft-file-rename
  :desc "count words" "x" #'zetteldeft-count-words)

(setq bibtex-autokey-name-year-separator ""
      bibtex-autokey-year-title-separator ""
      bibtex-autokey-year-length 4
      bibtex-autokey-titleword-length 0
      bibtex-autokey-titlewords 0)

(setq bibtex-align-at-equal-sign t
      bibtex-comma-after-last-field t
      bibtex-entry-format '(opts-or-alts required-fields numerical-fields realign last-comma sort-fields) )

(setq-default bibtex-maintain-sorted-entries t)

(setq bibtex-completion-bibliography '("/Users/ste/texmf/bibtex/bib/linguistics.bib")
      bibtex-completion-library-path '("/Users/ste/Library/Mobile Documents/com~apple~CloudDocs/drive/biblio")
      bibtex-completion-notes-path "/Users/ste/Library/Mobile Documents/com~apple~CloudDocs/drive/roam")

(setq reftex-default-bibliography '("/Users/ste/texmf/bibtex/bib/linguistics.bib"))

;; see org-ref for use of these variables
(setq org-ref-bibliography-notes "/Users/ste/Library/Mobile Documents/com~apple~CloudDocs/drive/roam"
      org-ref-default-bibliography '("/Users/ste/texmf/bibtex/bib/linguistics.bib")
      org-ref-pdf-directory "/Users/ste/Library/Mobile Documents/com~apple~CloudDocs/drive/biblio")

;; define markdown citation formats
(defvar markdown-cite-format)
(setq markdown-cite-format
      '(
        (?\C-m . "[@%l]")
        (?p . "[@%l]")
        (?t . "@%l")
        )
      )

;; wrap reftex-citation with local variables for markdown format
(defun markdown-reftex-citation ()
  (interactive)
  (let ((reftex-cite-format markdown-cite-format)
        (reftex-cite-key-separator "; @"))
    (reftex-citation)))

;; bind modified reftex-citation to C-c[, without enabling reftex-mode
;; https://www.gnu.org/software/auctex/manual/reftex/Citations-Outside-LaTeX.html#SEC31
(add-hook
 'markdown-mode-hook
 (lambda ()
   (define-key markdown-mode-map "\C-c[" 'markdown-reftex-citation)))

(load! "lexurgy-mode.el")

(setq load-path (cons "~/emacs" load-path))
(autoload 'lexurgy-mode "lexurgy" "Enter Lexurgy mode." t)
(setq auto-mode-alist (cons '("\\.lsc$" . lexurgy-mode) auto-mode-alist))
(autoload 'lexurgy-wlm-mode "lexurgy wlm" "Enter Lexurgy WLM mode." t)
(setq auto-mode-alist (cons '("\\.wl\\(m\\|i\\)$" . lexurgy-wlm-mode) auto-mode-alist))

(setq markdown-code-lang-modes
  '(("ocaml" . tuareg-mode) ("elisp" . emacs-lisp-mode) ("ditaa" . artist-mode)
    ("asymptote" . asy-mode) ("dot" . fundamental-mode) ("sqlite" . sql-mode)
    ("calc" . fundamental-mode) ("C" . c-mode) ("cpp" . c++-mode)
    ("C++" . c++-mode) ("screen" . shell-script-mode) ("shell" . sh-mode)
    ("bash" . sh-mode) ("=latex" . latex-mode)))

(load! "praat-script-mode.el")

(setq load-path (cons "~/emacs" load-path))
(autoload 'praat-script-mode "praat" "Enter Praat mode." t)
(setq auto-mode-alist (cons '("\\.praat$" . praat-script-mode) auto-mode-alist))

(setq ess-ask-for-ess-directory nil)

(add-to-list 'auto-mode-alist
             '("\\.secrets\\'" . ess-r-mode))

(add-to-list 'auto-mode-alist
             '("\\.rstheme\\'" . css-mode))

(add-to-list 'auto-mode-alist
             '("\\.Rproj$" . yaml-mode))

(after! org
  (setq org-startup-numerated nil)
  (setq org-startup-folded t))

(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))

(after! org
  (setq org-agenda-files '("/Users/ste/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/agenda.org"))
  (setq org-agenda-span 14)
  (setq org-agenda-start-on-weekday 1)
  (setq org-directory "/Users/ste/Library/Mobile Documents/com~apple~CloudDocs/drive/roam"))

(add-hook 'org-agenda-finalize-hook
  (lambda ()
    (save-excursion
      (color-org-header "Meetings:" "SeaGreen" "white")
      (color-org-header "Attend:" "DarkOrange" "black")
      (color-org-header "Engage:" "MediumPurple" "white")
      (color-org-header "Personal:" "red4" "white"))))

(defun color-org-header (tag backcolor forecolor)
  ""
  (interactive)
  (goto-char (point-min))
  (while (re-search-forward tag nil t)
    (add-text-properties (match-beginning 0) (+ (match-beginning 0) 10)
                     `(face (:background, backcolor, :foreground, forecolor)))))

(add-hook 'org-agenda-mode-hook 'org-fancy-priorities-mode)

(after! org-fancy-priorities
  (setq org-priority-faces '((?A :foreground "#e45649")
                             (?B :foreground "#da8548")
                             (?C :foreground "#0098dd"))
        org-fancy-priorities-list '("⬢" "⬢" "⬢")))
